### ISSUE TITLE
Display CI link in the thread of the PR :)

### ISSUE THREAD

**Issue by jjanvier** [SamirBoulil/slub#63]

**Comment by SamirBoulil** [comment]
I thought having it in the original message was enough to find the PR link:
![Screenshot 2019-09-09 at 10 44 48](https://user-images.githubusercontent.com/1826473/64516601-06866b00-d2ef-11e9-8fb5-a4b90e210576.png)

**Comment by SamirBoulil** [comment]
I've merged the functionality. Let me know if you experience any issue with it.
Cheerz
