### ISSUE TITLE
Talk to @Yeee to get the list of PRs to review

### ISSUE THREAD

**Issue by ValentinMumble** [SamirBoulil/slub#69]
Would it be possible to add a @Yeee command to get the list of all PRs to review in a channel?
Thank you my Sam! <3

**Comment by SamirBoulil** [comment]
Multiple parts to this question:
- The "Reminders" feature I've added to the #squad-raccoons channel gives us already a good view of the PRs to review for the day in my opinion (yet I know it's not perfect and not meant to do what you ask for)
- Maybe I'll add this feature in the future, but how ? when talking directly to @yeee ? talking to him directly in the channel ? I don't want @yeee to be talking too much, he should be present for important events. BUT why not! but let's see where I think would be the best way to do such thing  ⬇️ 
- The way I'm thinking more and more about @yeee, is too improve the sync between what yeee knows and what we can do in github:
    - A good example is the "to review" label of the PR that we rarely put on but is still required for each developper to set. Today, when a user puts a PR to review in slack, @yeee captures this intention but does not put this label on.
    - Where I want to go with @yeee is for it to put as much relevant information in Slack (like it does today) and also in Github (in the future)
    - Hence, when you want the list of PRs to review for your team, you do not go to @yeee for it, you go in Github pull requests (and since @yeee has synchronized the PR with everything it knows the search result is relevant and even more precise that just relying on what @yeee has captured on Slack).

So following what I've said above, I don't think I'll be doing this feature any time soon ^^.

I think the issue of "having an up to date list of PRs to review of my team" is important will be fixed but I think what you propose might not be the best way for yeee to go right now.
